//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Lat { get; set; }
        public string BusinessManager { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual User User { get; set; }
        public virtual Category Category { get; set; }
    }
}
