//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.UserCoupons = new HashSet<UserCoupon>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double OriginalPrice { get; set; }
        public double DiscountPrice { get; set; }
        public Nullable<double> AVGRate { get; set; }
        public System.DateTime LastUseDate { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<UserCoupon> UserCoupons { get; set; }
    }
}
