//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserCoupons = new HashSet<UserCoupon>();
            this.Businesses = new HashSet<Business>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Phonenumer { get; set; }
        public string Email { get; set; }
        public Nullable<int> FavoriteCategoryID { get; set; }
        public string CurrentLocation { get; set; }
        public int UserType { get; set; }
        public Nullable<int> RecommendationType { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual RecommendationType RecommendationType1 { get; set; }
        public virtual UserType UserType1 { get; set; }
        public virtual ICollection<UserCoupon> UserCoupons { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
    }
}
