//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCoupon
    {
        public int CouponID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Rate { get; set; }
        public bool Status { get; set; }
        public int SerialKey { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual User User { get; set; }
    }
}
